# Generated by Django 5.1.3 on 2025-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sueldo',
            field=models.FloatField(null=True),
        ),
    ]
