# Generated by Django 5.1.3 on 2025-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(choices=[('EM', 'Emisiones'), ('FR', 'Frenos'), ('DI', 'Direccion')], max_length=2, null=True),
        ),
    ]
