# Generated by Django 5.1.3 on 2025-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0002_usuario_apellidos_alter_usuario_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(choices=[('EM', 'Emisiones'), ('FR', 'Frenos'), ('DI', 'Direccion')], default='', max_length=2, null=True),
        ),
    ]
