# Generated by Django 5.1.3 on 2025-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0003_alter_usuario_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('EM', 'Emisiones'), ('FR', 'Frenos'), ('DI', 'Direccion')], max_length=2),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='puesto',
            field=models.CharField(choices=[('', ''), ('EM', 'Emisiones'), ('FR', 'Frenos'), ('DI', 'Direccion')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(choices=[('', ''), ('EM', 'Emisiones'), ('FR', 'Frenos'), ('DI', 'Direccion')], max_length=2, null=True),
        ),
    ]
