# Generated by Django 5.1.3 on 2025-01-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0004_cliente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
