# Generated by Django 5.1.3 on 2025-01-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0006_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
