# Generated by Django 5.1.3 on 2025-01-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITV', '0009_alter_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puesto',
        ),
    ]
